
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  mail:
    host: smtp.gmail.com
    port: 587
    username: your gmail address
    password: you gmail app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
encryption:
  salt:
    rounds: 10
jwt:
  secret:
    key: AL3MOS582WX2VX458923150FSDfOLR78520034ASD3PSV5A20ASD6QAP5ADS520Z